#!/bin/bash
#

SAMPLES="CTBPkdn_1 CTBPkdn_2 CTBPkdn_3 CTBPkdn_4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for sample in ${SAMPLES}
do
  mkdir ./${sample}
  cd ./${sample}
  \cp ../Makefile_PEreadPreparation_template ./Makefile_PEreadPreparation_${sample}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = ${sample}/;" ./Makefile_PEreadPreparation_${sample}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_PEreadPreparation_${sample}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_PEreadPreparation_${sample} >& ./err_${sample}) &
  cd ..
done
wait

SAMPLES="CTBPctl_1 CTBPctl_2 CTBPctl_3 CTBPctl_4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4
for sample in ${SAMPLES}
do
  mkdir ./${sample}
  cd ./${sample}
  \cp ../Makefile_PEreadPreparation_template ./Makefile_PEreadPreparation_${sample}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = ${sample}/;" ./Makefile_PEreadPreparation_${sample}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_PEreadPreparation_${sample}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_PEreadPreparation_${sample} >& ./err_${sample}) &
  cd ..
done
wait
