#!/bin/bash
#

workdir=${PWD}/../..
rawData_dir=${workdir}/RNA_seq/2_PRDM16KO/1_Raw_Reads
cleanReads_dir=${workdir}/RNA_seq/2_PRDM16KO/2_Cleaning_Reads


cd ${cleanReads_dir}
bash ${cleanReads_dir}/xqctrl


# Summary:
#
bash ${cleanReads_dir}/xln

seqkit stats -j 13 *fq > summary.stats
seqkit stats -j 13 *fq -T > summary.tsv

cd ..
