#!/bin/bash


cd ./4_DGE_Analysis


###For PAX6 PRDM16 RNA-seq
cd ./1_PAX6

# 1. Create the raw counts and samples to condition matrices
bash ./x1_createMatrices_PPC

# 2. Perform the differential gene expression analysis with R
bash ./x2a_DGE_analysis_PPC

# 3. Get the list of genes that will be used for the gene ontology analysis
bash ./x3_getgenes_PPC

cd ..


###For TBR2 PRDM16 RNA-seq
cd ./2_TBR2

# 1. Create the raw counts and samples to condition matrices
bash ./x1_createMatrices_TPC

# 2. Perform the differential gene expression analysis with R
bash ./x2a_DGE_analysis_TPC

# 3. Get the list of genes that will be used for the gene ontology analysis
bash ./x3_getgenes_TPC

cd ../..
