#!/bin/bash
#

workdir=${PWD}/../..
RNS_dir_PPC=${workdir}/RNA_seq/2_PRDM16KO/4_DGE_Analysis/1_PAX6
RNS_dir_TPC=${workdir}/RNA_seq/2_PRDM16KO/4_DGE_Analysis/2_TBR2
RNS_dir_combined=${workdir}/RNA_seq/2_PRDM16KO/5_Combine_PAX6_TBR2

# Concatenate a list of dysregulated genes from both the PAX6 and TBR2 positive cells experiments
cat ${RNS_dir_PPC}/v3a_PRDM16_PPC_upOrDownReg_genes.txt ${RNS_dir_TPC}/v3a_PRDM16_TPC_upOrDownReg_genes.txt | sort | uniq > ${RNS_dir_combined}/v1_upOrDownReg_genes_PRDM16_combined.txt

cat ${RNS_dir_PPC}/v3b_PRDM16_PPC_upReg_genes.txt ${RNS_dir_TPC}/v3b_PRDM16_TPC_upReg_genes.txt | sort | uniq > ${RNS_dir_combined}/v2_upReg_genes_PRDM16_combined.txt

cat ${RNS_dir_PPC}/v3c_PRDM16_PPC_downReg_genes.txt ${RNS_dir_TPC}/v3c_PRDM16_TPC_downReg_genes.txt | sort | uniq > ${RNS_dir_combined}/v3_downReg_genes_PRDM16_combined.txt
