#!/bin/bash
#
shopt -s expand_aliases

# Run this script from within the PRDM16_CtBP_Project singularity container, e.g.
# with "rws" specified as follows:
#
workdir=${PWD}/..
SIF=${workdir}/Tools/PRDM16_CtBP_Project.sif

alias rws="singularity exec -e -B${workdir} ${SIF}"


# 1. Acquiring the raw data for the H3K4me3 ChIP-Seq replicates from different developmental stages
rws bash ./x1_download_raw_reads

#    Derive summary statistics:
cd ./1_Raw_Reads
rws seqkit stats -j 10 *.fastq > summary.stats
rws seqkit stats -j 10 *.fastq -T > summary.tsv
cd ..


# 2. Clean the raw reads and run a quality check on them
rws bash ./x2_clean_raw_reads


# 3. Align the cleaned raw reads into the the reference genome
rws bash ./x3_map_reads


# 4. Call the peaks and process them by filtering out blacklist regions and reproducing them + annotating the CTBP2 peaks
rws bash ./x4a_callPeaks
rws bash ./x4b_filterBlacklistRegions >& ./y4b_filterBlacklistRegions_log.txt
rws bash ./x4c_1_reproducePeaks
rws bash ./x4d_annotateCTBP2Peaks >& y4d_annotateCTBP2Peaks_log.txt


# 5. Generate the bigWig files and perform the spike-in normalization for the spiked-in samples
rws bash ./x5a_get_bigWigs >& y5a_get_bigWigs_log.txt
rws bash ./x5b_1_countReadsForSpikeIn > y5b_1_countReadsForSpikeIn_log.txt
rws bash ./x5b_2_get_bigWigs_spike_in >& y5b_2_get_bigWigs_spike_in_log.txt
rws bash ./x5c_BW_Average
