#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/..
SIF=${workdir}/Tools/PRDM16_CtBP_Project.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"


RAW_DATA_dir=${workdir}/ChIP_seq/1_Raw_Reads



#This is a for loop that downloads the previously published ChIP-seq raw data that we used for our paper
#
for acc in SRR6823762 SRR6823763 SRR6823764 SRR6823765 SRR6823766 SRR6823767 SRR6823768 SRR6823769 SRR6823782 SRR6823783 SRR6823784 SRR6823785 SRR6823786 SRR6823787 SRR6823788 SRR6823789 SRR6823790 SRR6823791 SRR6823774 SRR6823775 SRR6823776 SRR6823777 SRR3651517 SRR3651670 SRR3651516 SRR3651669 SRR578278 SRR489727 SRR578279 SRR578284 
do
	echo ${acc} >> ${RAW_DATA_dir}/download.log
	rws fasterq-dump ${acc} >> ${RAW_DATA_dir}/download.log 2>&1
	echo -e "\n" >> ${RAW_DATA_dir}/download.log
done
echo -e "\n" >> ${RAW_DATA_dir}/download.log


# Move the raw data files to the "1_Raw_Reads" directory and rename them accordingly
mv SRR* ${RAW_DATA_dir}

cat ${RAW_DATA_dir}/SRR6823762.fastq ${RAW_DATA_dir}/SRR6823763.fastq > ${RAW_DATA_dir}/chs_PRDM16_e_1.fastq
cat ${RAW_DATA_dir}/SRR6823764.fastq ${RAW_DATA_dir}/SRR6823765.fastq > ${RAW_DATA_dir}/chs_INPUT_PRDM16_e_1.fastq

cat ${RAW_DATA_dir}/SRR6823766.fastq ${RAW_DATA_dir}/SRR6823767.fastq > ${RAW_DATA_dir}/chs_PRDM16_e_2.fastq
cat ${RAW_DATA_dir}/SRR6823768.fastq ${RAW_DATA_dir}/SRR6823769.fastq > ${RAW_DATA_dir}/chs_INPUT_PRDM16_e_2.fastq

cat ${RAW_DATA_dir}/SRR6823782.fastq ${RAW_DATA_dir}/SRR6823783.fastq ${RAW_DATA_dir}/SRR6823784.fastq > ${RAW_DATA_dir}/chs_H3K27ac_e_1.fastq
cat ${RAW_DATA_dir}/SRR6823785.fastq ${RAW_DATA_dir}/SRR6823786.fastq > ${RAW_DATA_dir}/chs_INPUT_H3K27ac_e_1.fastq

cat ${RAW_DATA_dir}/SRR6823787.fastq ${RAW_DATA_dir}/SRR6823788.fastq ${RAW_DATA_dir}/SRR6823789.fastq > ${RAW_DATA_dir}/chs_H3K27ac_e_2.fastq
cat ${RAW_DATA_dir}/SRR6823790.fastq ${RAW_DATA_dir}/SRR6823791.fastq > ${RAW_DATA_dir}/chs_INPUT_H3K27ac_e_2.fastq

mv ${RAW_DATA_dir}/SRR6823774.fastq ${RAW_DATA_dir}/chs_H3K4me1_e_1.fastq
mv ${RAW_DATA_dir}/SRR6823775.fastq ${RAW_DATA_dir}/chs_INPUT_H3K4me1_e_1.fastq
mv ${RAW_DATA_dir}/SRR6823776.fastq ${RAW_DATA_dir}/chs_H3K4me1_e_2.fastq
mv ${RAW_DATA_dir}/SRR6823777.fastq ${RAW_DATA_dir}/chs_INPUT_H3K4me1_e_2.fastq
mv ${RAW_DATA_dir}/SRR3651517.fastq ${RAW_DATA_dir}/chs_H3K4me3_e_1.fastq
mv ${RAW_DATA_dir}/SRR3651670.fastq ${RAW_DATA_dir}/chs_INPUT_H3K4me3_e_1.fastq
mv ${RAW_DATA_dir}/SRR3651516.fastq ${RAW_DATA_dir}/chs_H3K4me3_e_2.fastq
mv ${RAW_DATA_dir}/SRR3651669.fastq ${RAW_DATA_dir}/chs_INPUT_H3K4me3_e_2.fastq
mv ${RAW_DATA_dir}/SRR578278.fastq ${RAW_DATA_dir}/chs_CTCF_wb_1.fastq
mv ${RAW_DATA_dir}/SRR489727.fastq ${RAW_DATA_dir}/chs_INPUT_CTCF_wb_1.fastq
mv ${RAW_DATA_dir}/SRR578279.fastq ${RAW_DATA_dir}/chs_CTCF_wb_2.fastq
mv ${RAW_DATA_dir}/SRR578284.fastq ${RAW_DATA_dir}/chs_INPUT_CTCF_wb_2.fastq

\rm ${RAW_DATA_dir}/SRR*fastq
