#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/..
SIF=${workdir}/Tools/PRDM16_CtBP_Project.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"


rawData_dir=${workdir}/ChIP_seq/1_Raw_Reads
cleanReads_dir=${workdir}/ChIP_seq/2_Cleaning_Reads


cd ${cleanReads_dir}
rws bash ${cleanReads_dir}/xqctrl_SE
rws bash ${cleanReads_dir}/xqctrl_PE


# Summary:
#
bash ${cleanReads_dir}/xmv

rws seqkit stats -j 13 *fq > summary.stats
rws seqkit stats -j 13 *fq -T > summary.tsv

cd ..
