#!/bin/bash
#

workdir=${PWD}/..
rawData_dir=${workdir}/ChIP_seq/1_Raw_Reads
cleanReads_dir=${workdir}/ChIP_seq/2_Clean_Reads


cd ${cleanReads_dir}
bash ${cleanReads_dir}/xqctrl_SE
bash ${cleanReads_dir}/xqctrl_PE


# Summary:
#
bash ${cleanReads_dir}/xmv

rws seqkit stats -j 13 *fq    > summary.stats
rws seqkit stats -j 13 *fq -T > summary.tsv

cd ..
