#!/bin/bash
#

workdir=${PWD}/..
peaks_dir=${workdir}/ChIP_seq/4_Peaks
REP_PEAKS_dir=${peaks_dir}/Reproduced_Peaks



#This script is called from the x4c_1_reproducePeaks bash script and
# generates the log file y4c_logfile for the reproduced peaks.
#

echo 'The reproduced peaks for all the experiments except for CTBP2:'
echo ''
# To make a log for the reproduced peaks for the all the ChIP-seq experiments except for CTBP2
for sample in PRDM16_e HDAC1_e LSD1_e CTCF_wb H3K4me3_e H3K27ac_e H3K4me1_e
do
   echo ${sample}'_1 has' "$(grep -c . ${peaks_dir}/${sample}_1/${sample}_1_filtered.bed)" 'peaks.' ${sample}'_2 has' "$(grep -c . ${peaks_dir}/${sample}_2/${sample}_2_filtered.bed)" 'peaks.' 
   echo "$(grep -c . ${REP_PEAKS_dir}/${sample}_final_peaks.bed)" ${sample} 'peaks were reproduced.'
   echo ''
done


# Spacing
echo ''
echo ''
echo 'CTBP2 reproduced peaks:'
echo ''


# To make a log for the union set of peaks for the CTBP2 experiments
for CTBP2peakFile in CTBP2_e CTBP2wt_n
do 
   echo ${CTBP2peakFile}'_1' 'has' "$(grep -c . ${peaks_dir}/${CTBP2peakFile}_1/${CTBP2peakFile}_1_filtered.bed)" 'peaks.' ${CTBP2peakFile}'_2' 'has' "$(grep -c . ${peaks_dir}/${CTBP2peakFile}_2/${CTBP2peakFile}_2_filtered.bed)" 'peaks.' 
   echo 'The union set of peaks for' ${CTBP2peakFile} 'is' "$(grep -c . ${REP_PEAKS_dir}/${CTBP2peakFile}_union_peaks.bed)"
   echo ''
done


# To make a log for the final NSC CTBP2 peaks
echo 'The CTBP2_e union set has' "$(grep -c . ${REP_PEAKS_dir}/CTBP2_e_union_peaks.bed)" 'peaks.' 'The CTBP2wt_n union set has' "$(grep -c . ${REP_PEAKS_dir}/CTBP2wt_n_union_peaks.bed)" 'peaks.' 
echo 'The number of CTBP2_e and CTBP2wt_n reproduced peaks is '"$(grep -c . ${REP_PEAKS_dir}/CTBP2_NSC_final_peaks.bed)"'.'
