#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/..
SIF=${workdir}/Tools/PRDM16_CtBP_Project.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"



peaks_dir=${workdir}/ChIP_seq/4_Peaks
REP_PEAKS_dir=${peaks_dir}/z1_Reproduced_Peaks
annotated_peaks_dir=${peaks_dir}/z2_Annotated_Peaks


#Annotate the CTBP2 peaks and get percentages of their annotations in log files

experiment="CTBP2_NSC"

rws annotatePeaks.pl \
         ${REP_PEAKS_dir}/${experiment}_final_peaks.bed \
         mm39 \
         -size given \
         > ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt
   
awk -F'\t' '{print $8}' ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt | grep "exon" > ${annotated_peaks_dir}/${experiment}_exon_lines.txt
awk -F'\t' '{print $8}' ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt | grep "intron" > ${annotated_peaks_dir}/${experiment}_intron_lines.txt
awk -F'\t' '{print $8}' ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt | grep "Intergenic" > ${annotated_peaks_dir}/${experiment}_Intergenic_lines.txt
awk -F'\t' '{print $8}' ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt | grep "promoter-TSS" > ${annotated_peaks_dir}/${experiment}_promoter_lines.txt
awk -F'\t' '{print $8}' ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt | grep "TTS" > ${annotated_peaks_dir}/${experiment}_TTS_lines.txt

#the "wh" in all_lines_wh stands for "with header". The header is an additional line that we need to remove from the counting as done in all_lines_int
all_lines_wh=$(grep -c . ${annotated_peaks_dir}/${experiment}_annotated_peaks.txt)
all_lines_int=$(echo "$all_lines_wh - 1" | bc)
all_lines=$(echo "$all_lines_int + 0.0" | bc)
exon_lines_int=$(grep -c . ${annotated_peaks_dir}/${experiment}_exon_lines.txt) 
exon_lines=$(echo "$exon_lines_int + 0.0" | bc)
intronic_lines_int=$(grep -c . ${annotated_peaks_dir}/${experiment}_intron_lines.txt)
intronic_lines=$(echo "$intronic_lines_int + 0.0" | bc)
intergenic_lines_int=$(grep -c . ${annotated_peaks_dir}/${experiment}_Intergenic_lines.txt)
intergenic_lines=$(echo "$intergenic_lines_int + 0.0" | bc)
promoter_lines_int=$(grep -c . ${annotated_peaks_dir}/${experiment}_promoter_lines.txt) 
promoter_lines=$(echo "$promoter_lines_int + 0.0" | bc)
TTS_lines_int=$(grep -c . ${annotated_peaks_dir}/${experiment}_TTS_lines.txt) 
TTS_lines=$(echo "$TTS_lines_int + 0.0" | bc)

a=$(echo "scale=2; $exon_lines * 100 / $all_lines" | bc)
b=$(echo "scale=2; $intronic_lines * 100 / $all_lines" | bc)
c=$(echo "scale=2; $intergenic_lines * 100 / $all_lines" | bc)
d=$(echo "scale=2; $promoter_lines * 100 / $all_lines" | bc)
e=$(echo "scale=2; $TTS_lines * 100 / $all_lines" | bc)

echo "The number of reproduced" ${experiment%_*} "peaks is" $all_lines_int > ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The number of exonic" ${experiment%_*} "peaks is" $exon_lines_int >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The number of intronic" ${experiment%_*} "peaks is" $intronic_lines_int >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The number of intergenic" ${experiment%_*} "peaks is" $intergenic_lines_int >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The number of promoter" ${experiment%_*} "peaks is" $promoter_lines_int >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The number of TTS" ${experiment%_*} "peaks is" $TTS_lines_int >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The percentage of exonic" ${experiment%_*} "peaks is" $a"%" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The percentage of intronic" ${experiment%_*} "peaks is" $b"%" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The percentage of intergenic" ${experiment%_*} "peaks is" $c"%"  >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The percentage of promoter" ${experiment%_*} "peaks is" $d"%"  >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "" >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt
echo "The percentage of TTS" ${experiment%_*} "peaks is" $e"%"  >> ${annotated_peaks_dir}/Percentages_${experiment}_peaks.txt

rm -rf ${annotated_peaks_dir}/${experiment}_exon_lines.txt
rm -rf ${annotated_peaks_dir}/${experiment}_intron_lines.txt
rm -rf ${annotated_peaks_dir}/${experiment}_Intergenic_lines.txt
rm -rf ${annotated_peaks_dir}/${experiment}_promoter_lines.txt
rm -rf ${annotated_peaks_dir}/${experiment}_TTS_lines.txt



#Get the CTBP2 peaks that are annotated as promoter peaks

cd ${annotated_peaks_dir}

grep promoter ./CTBP2_NSC_annotated_peaks.txt > CTBP2_NSC_promoter_peaks_to_clean.bed

cut -d$'\t' -f2- CTBP2_NSC_promoter_peaks_to_clean.bed > CTBP2_NSC_promoter_peaks.bed

rm -rf CTBP2_NSC_promoter_peaks_to_clean.bed


grep Intergenic ./CTBP2_NSC_annotated_peaks.txt > CTBP2_NSC_Intergenic_peaks_to_clean.bed

cut -d$'\t' -f2- CTBP2_NSC_Intergenic_peaks_to_clean.bed > CTBP2_NSC_Intergenic_peaks.bed

rm -rf CTBP2_NSC_Intergenic_peaks_to_clean.bed


grep intron ./CTBP2_NSC_annotated_peaks.txt > CTBP2_NSC_intron_peaks_to_clean.bed

cut -d$'\t' -f2- CTBP2_NSC_intron_peaks_to_clean.bed > CTBP2_NSC_intron_peaks.bed

rm -rf CTBP2_NSC_intron_peaks_to_clean.bed

cd ../..
