#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/../../..
SIF=${workdir}/Tools/CTBPprj.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"


# 1. Aligning the reads to the mm39 mouse genome:
#
rws ./xbt2VSmm39 >& log



# 2. Checking on the alignment results:
#
rws ./xPEmapping_success

#
# ... produces *.mapped.PEread.counts, PEmapping_success.summary (which
#  should show 100% for all samples because the *.bam files should include only
#  properly mapped reads/pairs at this point), and PEread_processing.summary
#  (which gives a table of surviving read numbers from the original downloads
#  through the stages of trimming, dusting, and mapping; percentages are
#  calculated relative to the original download sets). 


# 3. Clean-up:
#
mkdir LOGFILES
mv log* *counts LOGFILES
