#!/bin/bash
#

workdir=${PWD}/../../..

# Map the RNA-seq reads using the STAR aligner:
#
NTHREADS=12
STARidx=../../../Genomes/genomeMM39/mm39STARidx
GTFfile=../../../Genomes/genomeMM39/mm39.gtf
SAMPLES="CTBPctl_1 CTBPctl_2 CTBPctl_3 CTBPctl_4 CTBPkdn_1 CTBPkdn_2 CTBPkdn_3 CTBPkdn_4"

for sample in ${SAMPLES}
do
  STAR --runThreadN ${NTHREADS} \
	--genomeDir ${STARidx} \
	--readFilesIn ../2_Cleaning_Reads/${sample}_R1.fq ../2_Cleaning_Reads/${sample}_R2.fq \
	--outFileNamePrefix ${sample}_ \
	--outSAMattributes All --outSAMtype BAM SortedByCoordinate \
	--outFilterMismatchNmax 10 --outFilterMultimapNmax 10 \
	--alignEndsType EndToEnd \
	--quantMode GeneCounts --twopassMode Basic \
	--sjdbGTFfile ${GTFfile}
  mkdir ${sample}
  mv ${sample}_* ${sample}
done
