#!/bin/bash


#Extracting the list of upregulated and downregulated genes

awk -F' ' '{print $1}' ./v2c_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v5a_CTBPkdn_upOrDownReg_genes.txt

awk -F' ' '{print $1}' ./v2d_CTBPkdn_DGE_Matrix_significantly_upReg.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v5b_CTBPkdn_upReg_genes.txt

awk -F' ' '{print $1}' ./v2e_CTBPkdn_DGE_Matrix_significantly_downReg.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v5c_CTBPkdn_downReg_genes.txt
