#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/..
SIF=${workdir}/Tools/PRDM16_CtBP_Project.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"



RAW_DATA_dir=${workdir}/ATAC_seq/1_Raw_Reads


#This is a for loop that downloads the previously published ATAC-seq raw data that we used for our paper
#
for acc in SRR14305471 SRR14305470	
do
	echo ${acc} >> ${RAW_DATA_dir}/download.log
	rws fasterq-dump ${acc} >> ${RAW_DATA_dir}/download.log 2>&1
	echo -e "\n" >> ${RAW_DATA_dir}/download.log
done


# Move the raw data files to the "1_Raw_Reads" directory and rename them accordingly
mv SRR* ${RAW_DATA_dir}

mv ${RAW_DATA_dir}/SRR14305471_1.fastq ${RAW_DATA_dir}/ats_e_1_R1.fastq
mv ${RAW_DATA_dir}/SRR14305471_2.fastq ${RAW_DATA_dir}/ats_e_1_R2.fastq

mv ${RAW_DATA_dir}/SRR14305470_1.fastq ${RAW_DATA_dir}/ats_e_2_R1.fastq
mv ${RAW_DATA_dir}/SRR14305470_2.fastq ${RAW_DATA_dir}/ats_e_2_R2.fastq
