#!/bin/bash
#

workdir=${PWD}/..
rawData_dir=${workdir}/ATAC_seq/1_Raw_Reads
cleanReads_dir=${workdir}/ATAC_seq/2_Clean_Reads


cd ${cleanReads_dir}
bash ${cleanReads_dir}/xqctrl_ats_e


# Summary:
#
bash ${cleanReads_dir}/xmv

seqkit stats -j 13 *fq > summary.stats
seqkit stats -j 13 *fq -T > summary.tsv

cd ..
