#!/bin/bash
#

workdir=${PWD}/..
BAM_files_dir=${workdir}/ATAC_seq/3_Alignments/bt2VSmm39
ref_dir=${workdir}/Genomes/genomeMM39
blacklist_regions=${ref_dir}/mm39.excluderanges.bed
OUTDIR_BW=./4_bigWigs

#Generating bigWig files with deepTools bamCoverage
for sampleATS in ats_e_1 ats_e_2
do
   echo ${sampleATS}':'
   echo ''
   bamCoverage \
         -b ${BAM_files_dir}/${sampleATS}.bam \
         -o ${OUTDIR_BW}/${sampleATS}.bw \
         --numberOfProcessors max \
         --binSize 10 \
         --blackListFileName ${blacklist_regions} \
         --extendReads \
         --smoothLength 100 \
         --centerReads \
         --ignoreDuplicates
   echo ''
   echo ''
done
