#!/bin/bash
#

workdir=${PWD}/..
ref_dir=${workdir}/Genomes/genomeMM39
blacklist_regions=${ref_dir}/mm39.excluderanges.bed
bigWig_DIR=./4_bigWigs

#Averaging the bigWig files with deepTools bigwigAverage

bigwigAverage \
      -b ${bigWig_DIR}/ats_e_1.bw ${bigWig_DIR}/ats_e_2.bw \
      --binSize 10 \
      --blackListFileName ${blacklist_regions} \
      --numberOfProcessors max \
      -of bigwig \
      -o ${bigWig_DIR}/ats_e_average.bw

