#!/bin/bash
#
shopt -s expand_aliases



# Specify the directory for the BAM files
workdir=${PWD}/../../../..
BAM_FILES_DIR=${workdir}/RNA_seq/2_PRDM16KO/3_Alignment
DGE_DIR=${workdir}/RNA_seq/2_PRDM16KO/4_DGE_Analysis/2_TBR2


# Extracting the gene names column
cut -d$'\t' -f1 ${BAM_FILES_DIR}/PRDM16_TPCwt1/PRDM16_TPCwt1_ReadsPerGene.out.tab > ./gene_column.tsv


# Extracting the needed columns from the gene counts files

RNS_EXPERIMENTS="PRDM16_TPCko1 PRDM16_TPCko2 PRDM16_TPCko3 PRDM16_TPCko4 PRDM16_TPCwt1 PRDM16_TPCwt2 PRDM16_TPCwt3 PRDM16_TPCwt4"

for experiment in ${RNS_EXPERIMENTS}
do
   cut -d$'\t' -f2 ${BAM_FILES_DIR}/${experiment}/${experiment}_ReadsPerGene.out.tab > ./${experiment}_counts_column.tsv
done


# Pasting the extracted columns in a raw counts matrix file and removing the temporary files

paste gene_column.tsv PRDM16_TPCwt1_counts_column.tsv PRDM16_TPCwt2_counts_column.tsv PRDM16_TPCwt3_counts_column.tsv PRDM16_TPCwt4_counts_column.tsv PRDM16_TPCko1_counts_column.tsv PRDM16_TPCko2_counts_column.tsv PRDM16_TPCko3_counts_column.tsv PRDM16_TPCko4_counts_column.tsv > PRDM16_TPC_raw_counts_to_clean.tsv

sed -i '1,4d' PRDM16_TPC_raw_counts_to_clean.tsv

echo -e "gene_id\tPRDM16_TPCwt1\tPRDM16_TPCwt2\tPRDM16_TPCwt3\tPRDM16_TPCwt4\tPRDM16_TPCko1\tPRDM16_TPCko2\tPRDM16_TPCko3\tPRDM16_TPCko4" > PRDM16_TPC_raw_counts_headers.tsv

cat PRDM16_TPC_raw_counts_headers.tsv PRDM16_TPC_raw_counts_to_clean.tsv > v1a_PRDM16_TPC_raw_counts.tsv

rm -rf gene_column.tsv
rm -rf *_counts_column.tsv
rm -rf PRDM16_TPC_raw_counts_*.tsv


# Creating the samples to conditions matrix

echo -e "sample\tcondition" > temp_row_1.tsv
echo -e "PRDM16_TPCwt1\tWT" > temp_row_2.tsv
echo -e "PRDM16_TPCwt2\tWT" > temp_row_3.tsv
echo -e "PRDM16_TPCwt3\tWT" > temp_row_4.tsv
echo -e "PRDM16_TPCwt4\tWT" > temp_row_5.tsv
echo -e "PRDM16_TPCko1\tKO" > temp_row_6.tsv
echo -e "PRDM16_TPCko2\tKO" > temp_row_7.tsv
echo -e "PRDM16_TPCko3\tKO" > temp_row_8.tsv
echo -e "PRDM16_TPCko4\tKO" > temp_row_9.tsv

cat temp_* > v1b_PRDM16_TPC_samples_to_conditions.tsv

rm -rf temp_*
