#!/bin/bash
#

#Extracting the list of upregulated and downregulated genes

awk -F' ' '{print $1}' ./v2c_PRDM16_TPC_DGE_Matrix_NA_omitted_filtered.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v3a_PRDM16_TPC_upOrDownReg_genes.txt

awk -F' ' '{print $1}' ./v2d_PRDM16_TPC_DGE_Matrix_significantly_upReg.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v3b_PRDM16_TPC_upReg_genes.txt

awk -F' ' '{print $1}' ./v2e_PRDM16_TPC_DGE_Matrix_significantly_downReg.tsv | sed 's/"//g' | sed '1d' | sort | uniq > ./v3c_PRDM16_TPC_downReg_genes.txt
