#!/bin/bash
#

bt2idx=../../../Genomes/genomeMM39/BSgenome.Mmusculus.UCSC.mm39chrs
FASTQdir=../../2_Clean_Reads
bt2_threads=16
st_threads=16
SAMPLE=$1


# 1. Map the paired-end reads from "SAMPLE" to the mm39 genome:
#
bowtie2 \
	--threads ${bt2_threads} --no-unal \
	-x ${bt2idx} \
	-1 ${FASTQdir}/${SAMPLE}_R1.fq \
	-2 ${FASTQdir}/${SAMPLE}_R2.fq \
	-S ./tmp_${SAMPLE}.sam

# 2. Select only properly mapped read pairs:
#
samtools view -H ./tmp_${SAMPLE}.sam \
	>  ./${SAMPLE}.sam
samtools view -@ ${st_threads} ./tmp_${SAMPLE}.sam \
	| awk '{if ($2 == 99 || $2 == 147 || $2 == 83 || $2 == 163) print $0}' \
	>> ./${SAMPLE}.sam

# 3. Make a sorted and indexed bam file from the sam file:
#
samtools view -h -b -@ ${st_threads} ./${SAMPLE}.sam \
	| samtools sort -@ ${st_threads} -o ${SAMPLE}.bam -
samtools index -@ ${st_threads} ./${SAMPLE}.bam

# 4. Clean up:
#
\rm tmp_${SAMPLE}.sam
