#!/bin/bash
#


# 1. Aligning the reads to the mm39 mouse genome:
#
bash ./xbt2VSmm39 >& log


# 2. Checking on the alignment results:
#
bash ./xPEmapping_success

#
# ... produces *.mapped.PEread.counts, PEmapping_success.summary (which
#  should show 100% for all samples because the *.bam files should include only
#  properly mapped reads/pairs at this point), and PEread_processing.summary
#  (which gives a table of surviving read numbers from the original downloads
#  through the stages of trimming, dusting, and mapping; percentages are
#  calculated relative to the original download sets). 


# 3. Clean-up:
#
mkdir LOGFILES
mv log* *counts LOGFILES
