#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/../../..


ln -s PRDM16_PPCko1/PRDM16_PPCko1_Aligned.sortedByCoord.out.bam ./PRDM16_PPCko1.bam
ln -s PRDM16_PPCko2/PRDM16_PPCko2_Aligned.sortedByCoord.out.bam ./PRDM16_PPCko2.bam
ln -s PRDM16_PPCko3/PRDM16_PPCko3_Aligned.sortedByCoord.out.bam ./PRDM16_PPCko3.bam
ln -s PRDM16_PPCko4/PRDM16_PPCko4_Aligned.sortedByCoord.out.bam ./PRDM16_PPCko4.bam
ln -s PRDM16_PPCwt1/PRDM16_PPCwt1_Aligned.sortedByCoord.out.bam ./PRDM16_PPCwt1.bam
ln -s PRDM16_PPCwt2/PRDM16_PPCwt2_Aligned.sortedByCoord.out.bam ./PRDM16_PPCwt2.bam
ln -s PRDM16_PPCwt3/PRDM16_PPCwt3_Aligned.sortedByCoord.out.bam ./PRDM16_PPCwt3.bam
ln -s PRDM16_PPCwt4/PRDM16_PPCwt4_Aligned.sortedByCoord.out.bam ./PRDM16_PPCwt4.bam
ln -s PRDM16_TPCko1/PRDM16_TPCko1_Aligned.sortedByCoord.out.bam ./PRDM16_TPCko1.bam
ln -s PRDM16_TPCko2/PRDM16_TPCko2_Aligned.sortedByCoord.out.bam ./PRDM16_TPCko2.bam
ln -s PRDM16_TPCko3/PRDM16_TPCko3_Aligned.sortedByCoord.out.bam ./PRDM16_TPCko3.bam
ln -s PRDM16_TPCko4/PRDM16_TPCko4_Aligned.sortedByCoord.out.bam ./PRDM16_TPCko4.bam
ln -s PRDM16_TPCwt1/PRDM16_TPCwt1_Aligned.sortedByCoord.out.bam ./PRDM16_TPCwt1.bam
ln -s PRDM16_TPCwt2/PRDM16_TPCwt2_Aligned.sortedByCoord.out.bam ./PRDM16_TPCwt2.bam
ln -s PRDM16_TPCwt3/PRDM16_TPCwt3_Aligned.sortedByCoord.out.bam ./PRDM16_TPCwt3.bam
ln -s PRDM16_TPCwt4/PRDM16_TPCwt4_Aligned.sortedByCoord.out.bam ./PRDM16_TPCwt4.bam


for file in PRDM16_PPCko1 PRDM16_PPCko2 PRDM16_PPCko3 PRDM16_PPCko4 PRDM16_PPCwt1 PRDM16_PPCwt2 PRDM16_PPCwt3 PRDM16_PPCwt4 PRDM16_TPCko1 PRDM16_TPCko2 PRDM16_TPCko3 PRDM16_TPCko4 PRDM16_TPCwt1 PRDM16_TPCwt2 PRDM16_TPCwt3 PRDM16_TPCwt4
do
  samtools index ${file}.bam
  bash ${workdir}/Tools/xcountSAMtypes ${file}.bam > ${file}.counts
done
