#!/bin/bash
#

workdir=${PWD}/../../..


# Map the RNA-seq reads using the STAR aligner:
#
NTHREADS=12
READS_dir=${workdir}/RNA_seq/2_PRDM16KO/2_Cleaning_Reads
STARidx=../../../Genomes/genomeMM39/mm39STARidx
GTFfile=../../../Genomes/genomeMM39/mm39.gtf
SAMPLES="PRDM16_PPCko1 PRDM16_PPCko2 PRDM16_PPCko3 PRDM16_PPCko4 PRDM16_PPCwt1 PRDM16_PPCwt2 PRDM16_PPCwt3 PRDM16_PPCwt4 PRDM16_TPCko1 PRDM16_TPCko2 PRDM16_TPCko3 PRDM16_TPCko4 PRDM16_TPCwt1 PRDM16_TPCwt2 PRDM16_TPCwt3 PRDM16_TPCwt4"


for sample in ${SAMPLES}
do
  STAR --runThreadN ${NTHREADS} \
	--genomeDir ${STARidx} \
	--readFilesIn ${READS_dir}/${sample}.fq \
	--outFileNamePrefix ${sample}_ \
	--outSAMattributes All --outSAMtype BAM SortedByCoordinate \
	--outFilterMismatchNmax 10 --outFilterMultimapNmax 10 \
	--alignEndsType EndToEnd \
	--quantMode GeneCounts --twopassMode Basic \
	--sjdbGTFfile ${GTFfile}
  mkdir ${sample}
  mv ${sample}_* ${sample}
done
