#!/bin/bash
#


DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

EXPERIMENT1="H3K4me3_e_1 INPUT_H3K4me3_e_1 H3K4me3_e_2 INPUT_H3K4me3_e_2"
EXPERIMENT2="CTCF_wb_1 INPUT_CTCF_wb_1 CTCF_wb_2 INPUT_CTCF_wb_2"

EXPERIMENT3="H3K4me1_e_1 INPUT_H3K4me1_e_1 H3K4me1_e_2 INPUT_H3K4me1_e_2"
EXPERIMENT4="H3K27ac_e_1 INPUT_H3K27ac_e_1 H3K27ac_e_2 INPUT_H3K27ac_e_2"
EXPERIMENT5="PRDM16_e_1 INPUT_PRDM16_e_1 PRDM16_e_2 INPUT_PRDM16_e_2"


for i in ${EXPERIMENT1} ${EXPERIMENT2}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait


for i in ${EXPERIMENT3} ${EXPERIMENT4} ${EXPERIMENT5}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#TMO-c      =                         30#TMO-c      =                         50#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait
