#!/bin/bash
#

SAMPLES="PRDM16_PPCwt1 PRDM16_PPCwt2 PRDM16_PPCwt3 PRDM16_PPCwt4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for i in ${SAMPLES}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait


SAMPLES="PRDM16_PPCko1 PRDM16_PPCko2 PRDM16_PPCko3 PRDM16_PPCko4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for i in ${SAMPLES}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait


SAMPLES="PRDM16_TPCwt1 PRDM16_TPCwt2 PRDM16_TPCwt3 PRDM16_TPCwt4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for i in ${SAMPLES}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait


SAMPLES="PRDM16_TPCko1 PRDM16_TPCko2 PRDM16_TPCko3 PRDM16_TPCko4"
DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for i in ${SAMPLES}
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_SEreadPreparation_template ./Makefile_SEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_SEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_SEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_SEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait
