#!/bin/bash
#
shopt -s expand_aliases

# Specify the working directory and the CTBPprj singularity image file:
#
workdir=${PWD}/../..
CONTAINER=${workdir}/Tools/CTBPprj.sif

alias rws="singularity exec -e -B${workdir} $CONTAINER"

NTHREADS=16
STARidx=./mm39STARidx
GENOME=./BSgenome.Mmusculus.UCSC.mm39chrs.fa
GTFfile=./mm39.gtf


# Generate the STAR index for mm39
rws  STAR \
	--runThreadN ${NTHREADS} \
	--runMode genomeGenerate \
	--genomeDir ${STARidx} \
	--genomeFastaFiles ${GENOME} \
	--sjdbGTFfile ${GTFfile}
