#!/bin/bash
#
shopt -s expand_aliases



# Specify the directory for the BAM files
workdir=${PWD}/../../..
BAM_FILES_DIR=${workdir}/RNA_seq/1_CTBPkdn/3_Alignment
DGE_DIR=${workdir}/RNA_seq/1_CTBPkdn/4_DGE_Analysis


# Extracting the gene names column
cut -d$'\t' -f1 ${BAM_FILES_DIR}/CTBPctl_1/CTBPctl_1_ReadsPerGene.out.tab > ./gene_column.tsv


# Extracting the needed columns from the gene counts files

RNS_EXPERIMENTS="CTBPctl_1 CTBPctl_2 CTBPctl_3 CTBPctl_4 CTBPkdn_1 CTBPkdn_2 CTBPkdn_3 CTBPkdn_4"

for experiment in ${RNS_EXPERIMENTS}
do
   cut -d$'\t' -f4 ${BAM_FILES_DIR}/${experiment}/${experiment}_ReadsPerGene.out.tab > ./${experiment}_counts_column.tsv
done


# Pasting the extracted columns in a raw counts matrix file and removing the temporary files

paste gene_column.tsv CTBPctl_1_counts_column.tsv CTBPctl_2_counts_column.tsv CTBPctl_3_counts_column.tsv CTBPctl_4_counts_column.tsv CTBPkdn_1_counts_column.tsv CTBPkdn_2_counts_column.tsv CTBPkdn_3_counts_column.tsv CTBPkdn_4_counts_column.tsv > CTBPkdn_raw_counts_to_clean.tsv

sed -i '1,4d' CTBPkdn_raw_counts_to_clean.tsv

echo -e "gene_id\tCTBPctl_1\tCTBPctl_2\tCTBPctl_3\tCTBPctl_4\tCTBPkdn_1\tCTBPkdn_2\tCTBPkdn_3\tCTBPkdn_4" > CTBPkdn_raw_counts_headers.tsv

cat CTBPkdn_raw_counts_headers.tsv CTBPkdn_raw_counts_to_clean.tsv > v1a_CTBPkdn_raw_counts.tsv

rm -rf gene_column.tsv
rm -rf *_counts_column.tsv
rm -rf CTBPkdn_raw_counts_*.tsv


# Creating the samples to conditions matrix

echo -e "sample\tcondition" > temp_row_1.tsv
echo -e "CTBPctl_1\tCTRL" > temp_row_2.tsv
echo -e "CTBPctl_2\tCTRL" > temp_row_3.tsv
echo -e "CTBPctl_3\tCTRL" > temp_row_4.tsv
echo -e "CTBPctl_4\tCTRL" > temp_row_5.tsv
echo -e "CTBPkdn_1\tKDN" > temp_row_6.tsv
echo -e "CTBPkdn_2\tKDN" > temp_row_7.tsv
echo -e "CTBPkdn_3\tKDN" > temp_row_8.tsv
echo -e "CTBPkdn_4\tKDN" > temp_row_9.tsv

cat temp_* > v1b_CTBPkdn_samples_to_conditions.tsv

rm -rf temp_*
