#!/bin/bash

shopt -s expand_aliases

# Specify directory for the container
workdir=${PWD}/../../..
SIF=${workdir}/Tools/RNA-Seq.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} $SIF"


#Executing the RNA-Seq DGE Analysis script

rws Rscript ./x2b_DGE_analysis.R


#Appropriately arranging the headers of the exported matrices

echo -e "gene_id\tbaseMean\tlog2FoldChange\tlfcSE\tstat\tpvalue\tpadj" > ./CTBPkdn_exported_matrices_header.tsv

sed -i '1d' ./v2a_CTBPkdn_DGE_Matrix.tsv
sed -i '1d' ./v2b_CTBPkdn_DGE_Matrix_NA_omitted.tsv
sed -i '1d' ./v2c_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv
sed -i '1d' ./v2d_CTBPkdn_DGE_Matrix_significantly_upReg.tsv
sed -i '1d' ./v2e_CTBPkdn_DGE_Matrix_significantly_downReg.tsv

cat ./CTBPkdn_exported_matrices_header.tsv \
./v2a_CTBPkdn_DGE_Matrix.tsv \
> ./v2a_improved_CTBPkdn_DGE_Matrix.tsv

cat ./CTBPkdn_exported_matrices_header.tsv \
./v2b_CTBPkdn_DGE_Matrix_NA_omitted.tsv \
> ./v2b_improved_CTBPkdn_DGE_Matrix_NA_omitted.tsv

cat ./CTBPkdn_exported_matrices_header.tsv \
./v2c_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv \
> ./v2c_improved_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv

cat ./CTBPkdn_exported_matrices_header.tsv \
./v2d_CTBPkdn_DGE_Matrix_significantly_upReg.tsv \
> ./v2d_improved_CTBPkdn_DGE_Matrix_significantly_upReg.tsv

cat ./CTBPkdn_exported_matrices_header.tsv \
./v2e_CTBPkdn_DGE_Matrix_significantly_downReg.tsv \
> ./v2e_improved_CTBPkdn_DGE_Matrix_significantly_downReg.tsv


rm -rf ./CTBPkdn_exported_matrices_header.tsv
rm -rf ./v2a_CTBPkdn_DGE_Matrix.tsv
rm -rf ./v2b_CTBPkdn_DGE_Matrix_NA_omitted.tsv
rm -rf ./v2c_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv
rm -rf ./v2d_CTBPkdn_DGE_Matrix_significantly_upReg.tsv
rm -rf ./v2e_CTBPkdn_DGE_Matrix_significantly_downReg.tsv


mv ./v2a_improved_CTBPkdn_DGE_Matrix.tsv \
./v2a_CTBPkdn_DGE_Matrix.tsv

mv ./v2b_improved_CTBPkdn_DGE_Matrix_NA_omitted.tsv \
./v2b_CTBPkdn_DGE_Matrix_NA_omitted.tsv

mv ./v2c_improved_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv \
./v2c_CTBPkdn_DGE_Matrix_NA_omitted_filtered.tsv

mv ./v2d_improved_CTBPkdn_DGE_Matrix_significantly_upReg.tsv \
./v2d_CTBPkdn_DGE_Matrix_significantly_upReg.tsv

mv ./v2e_improved_CTBPkdn_DGE_Matrix_significantly_downReg.tsv \
./v2e_CTBPkdn_DGE_Matrix_significantly_downReg.tsv
