#!/bin/bash
#

# 1. Mapping paired-end samples:
#
for exprmnt in CTBP2_e_1 CTBP2_e_2 HDAC1_e_1 HDAC1_e_2 INPUT_e_3 INPUT_e_4 LSD1_e_1 LSD1_e_2
do
  echo -e "\n\nNow running:\n./xmapPEbt2 ${exprmnt} >& log_${exprmnt}"
  time ./xmapPEbt2 ${exprmnt} >& log_${exprmnt}
done


# 2. Mapping single-end read samples:
#
for exprmnt in CTCF_wb_1 CTCF_wb_2 H3K27ac_e_1 H3K27ac_e_2 H3K4me1_e_1 H3K4me1_e_2 H3K4me3_e_1 H3K4me3_e_2 INPUT_CTCF_wb_1 INPUT_CTCF_wb_2 INPUT_H3K27ac_e_1 INPUT_H3K27ac_e_2 INPUT_H3K4me1_e_1 INPUT_H3K4me1_e_2 INPUT_H3K4me3_e_1 INPUT_H3K4me3_e_2 INPUT_PRDM16_e_1 INPUT_PRDM16_e_2 PRDM16_e_1 PRDM16_e_2 
do
  echo -e "\n\nNow running:\n./xmapSEbt2 ${exprmnt} >& log_${exprmnt}"
  time ./xmapSEbt2 ${exprmnt} >& log_${exprmnt}
done
