#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/..
SIF=${workdir}/Tools/chs_analysis.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"



#Averaging the bigWig files with deepTools bigwigAverage

ref_dir=${workdir}/Genomes/genomeMM39
blacklist_regions=${ref_dir}/mm39.excluderanges.bed

bigWig_DIR=./4_bigWigs


rws bigwigAverage \
      -b ${bigWig_DIR}/ats_e_1.bw ${bigWig_DIR}/ats_e_2.bw \
      --binSize 10 \
      --blackListFileName ${blacklist_regions} \
      --numberOfProcessors max \
      -of bigwig \
      -o ${bigWig_DIR}/ats_e_average.bw

