#!/bin/bash
#


DOWNLOADdir=../1_Raw_Reads
NTHREADS=4

for i in ats_e_1 ats_e_2
do
  mkdir ./${i}
  cd ./${i}
  \cp ../Makefile_PEreadPreparation_template ./Makefile_PEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" ./Makefile_PEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../${DOWNLOADdir}#;" ./Makefile_PEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f ./Makefile_PEreadPreparation_${i} >& ./err_${i}) &
  cd ..
done
wait
