#!/bin/bash
#
shopt -s expand_aliases


workdir=${PWD}/../..
SIF=${workdir}/Tools/CTBPprj.sif


#giving an alias for executing the singularity container
alias rws="singularity exec -e -B${workdir} ${SIF}"



rawData_dir=${workdir}/RNA_seq/1_CTBPkdn/1_Raw_Reads
cleanReads_dir=${workdir}/RNA_seq/1_CTBPkdn/2_Cleaning_Reads


cd ${cleanReads_dir}
rws bash ${cleanReads_dir}/xqctrl


# Summary:
#
bash ${cleanReads_dir}/xln

rws seqkit stats -j 13 *fq > summary.stats
rws seqkit stats -j 13 *fq -T > summary.tsv

cd ..
