#!/bin/bash
#

cd ./4_DGE_Analysis

# 1. Create the raw counts and samples to condition matrices
bash ./x1_createMatrices

# 2. Perform the differential gene expression analysis with R
bash ./x2a_DGE_analysis

# 3. Get the list of genes that will be used for the gene ontology analysis
bash ./x3_getgenes

cd ..
